In [1]:
import nltk
#nltk.download()

In [2]:
import numpy as np
import pandas as pd
import re
import sklearn
from sklearn.pipeline import Pipeline
from sklearn import svm
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score,accuracy_score,recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier
from KaggleWord2VecUtility import KaggleWord2VecUtility
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from nltk import bigrams
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
import keras.utils
#(X_train, y_train), (X_test, y_test) = imdb.load_data(nb_words=top_words)


data= pd.read_csv('/home/pramod/Transfer/temp/obamaupdate.csv')

clean_train_reviews = []
#bigramFeatureVector = []
train_data_features2=[]
xa=data["Anootated tweet"]
for i in xrange(0,len(data)):
    clean_train_reviews.append(" ".join(KaggleWord2VecUtility.review_to_wordlist(data["Anootated tweet"][i], False,True,False,True)))

clean_train_reviews=np.array(clean_train_reviews)
a=np.array(data["Class"][0:len(data)])

print type(a[1])
print type(clean_train_reviews[1])

cr=[x.encode('UTF8') for x in clean_train_reviews]


'''vectorizer = CountVectorizer(analyzer = "word",tokenizer = None, preprocessor = None,stop_words = None,max_features = 500) 

train_data_features=[]
train_data_features=vectorizer.fit_transform(clean_train_reviews).toarray()

#X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)

#print X_train.shape
#print y_train.shape
print train_data_features.shape
a=np.array(data["Class"][0:len(data)])
print a.shape
#b=np.array(train_data_features)
#print b.shape
model = Sequential()
model.add(Embedding(96603, 128, input_length=500))
model.add(LSTM(128))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])#In line two, we add an Embedding layer. This layer lets the network expand each token to a larger vector, allowing the network to represent words in a meaningful way. We pass 20000 as the first argument, which is the size of our vocabulary (remember, we told the tokenizer to only use the 20 000 most common words earlier), and 128 as the second, which means that each token can be expanded to a vector of size 128. We give it an input_length of 300, which is the length of each of our sequences.
print(model.summary())
model.fit(train_data_features, a , nb_epoch=1, batch_size=500)
# Final evaluation of the model
scores = model.evaluate(train_data_features,a, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))'''

Using TensorFlow backend.


<type 'numpy.int64'>
<type 'numpy.unicode_'>


'vectorizer = CountVectorizer(analyzer = "word",tokenizer = None, preprocessor = None,stop_words = None,max_features = 500) \n\ntrain_data_features=[]\ntrain_data_features=vectorizer.fit_transform(clean_train_reviews).toarray()\n\n#X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)\n\n#print X_train.shape\n#print y_train.shape\nprint train_data_features.shape\na=np.array(data["Class"][0:len(data)])\nprint a.shape\n#b=np.array(train_data_features)\n#print b.shape\nmodel = Sequential()\nmodel.add(Embedding(96603, 128, input_length=500))\nmodel.add(LSTM(128))\nmodel.add(Dense(1, activation=\'sigmoid\'))\nmodel.compile(loss=\'binary_crossentropy\', optimizer=\'adam\', metrics=[\'accuracy\'])#In line two, we add an Embedding layer. This layer lets the network expand each token to a larger vector, allowing the network to represent words in a meaningful way. We pass 20000 as the first argument, which is the size of our vocabulary (remember, we told the tokenizer to only use t

In [3]:
from keras.utils import np_utils
b= np_utils.to_categorical(a,3)


print b

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 ..., 
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]


In [4]:
from keras.layers import Embedding, LSTM, Dense, Conv1D, MaxPooling1D, Dropout, Activation
from keras.models import Sequential
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
x="my name is pramod"
tokenizer = Tokenizer(10000)
tokenizer.fit_on_texts(cr)
sequences = tokenizer.texts_to_sequences(cr)
data = pad_sequences(sequences, maxlen=200)

X_train, X_test, y_train, y_test = train_test_split( data , b, test_size=0.2, random_state=42)

print data.shape

(5625, 200)


In [ ]:
from keras import optimizers

model = Sequential()
model.add(Embedding(20000, 200, input_length=200))
model.add(LSTM(200))
model.add(Dense(3, activation='softmax'))
sgd = optimizers.SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=keras.optimizers.Adam(lr=0.0001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0), metrics=['accuracy'])
model.fit(data, b, nb_epoch=5)

Epoch 1/5
5625/5625 [==============================] - 192s 34ms/step - loss: 1.0794 - acc: 0.4220
Epoch 2/5
1472/5625 [======>.......................] - ETA: 2:30 - loss: 1.0499 - acc: 0.4484

In [ ]:
labels = pd.read_csv('/home/pramod/Desktop/romney.csv')
L=np.array(pd.DataFrame(labels["t"]))

data3 = pd.read_excel('/home/pramod/Downloads/Romney.xlsx')
tweets=np.array(pd.DataFrame(data3["tweet"]))


clean_test = []

for i in xrange(0,len(tweets)):
    clean_test.append(" ".join(KaggleWord2VecUtility.review_to_wordlist(tweets[i],False,True,False,False)))

test_labels=model.predict(clean_test)

print(classification_report(L, test_labels))




In [14]:
import keras.utils
from keras import optimizers

#a = keras.utils.to_categorical(a)
#set seed here
#using elu and leaky relu

model = Sequential()
model.add(Embedding(20000, 300, input_length=500))
model.add(Dropout(0.3))
model.add(Conv1D(64, 5, activation='relu'))
model.add(MaxPooling1D(4))
model.add(LSTM(300))
model.add(Dense(3, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train,nb_epoch=30,validation_split=0.2,batch_size=50)

Train on 3600 samples, validate on 900 samples
Epoch 1/30
3600/3600 [==============================] - 91s - loss: 1.0940 - acc: 0.3706 - val_loss: 1.0872 - val_acc: 0.4078

In [15]:
scores = model.evaluate(X_test, y_test, verbose=0)
print("Baseline Error: %.2f%%" % (100-scores[1]*100))
print ("test score is ",scores[0])
print ('test accuracy is ', scores[1])

Baseline Error: 42.76%
('test score is ', 1.2337377683851454)
('test accuracy is ', 0.57244444455040822)
